### ISSUE TITLE
Site logo design

### ISSUE THREAD

**Issue by pannkotsky** [pannkotsky/groupmate#38]

**Comment by irasober** [comment]
![bg](https://user-images.githubusercontent.com/33085717/32147194-22012566-bcec-11e7-946f-6d4175185ad6.png)
![favicon-big](https://user-images.githubusercontent.com/33085717/32147196-23511a20-bcec-11e7-9242-74eb57c99161.png)
![favicon-small](https://user-images.githubusercontent.com/33085717/32147198-27af7076-bcec-11e7-836d-13cc726219d9.png)

**Comment by irasober** [comment]
![logo](https://user-images.githubusercontent.com/33085717/32147211-623633d8-bcec-11e7-8611-c2b4069d2ea5.png)
